# Generated by Django 5.2.8 on 2025-11-27 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('layout', models.CharField(choices=[('layout1', 'Layout 1 - Imagem Grande'), ('layout2', 'Layout 2 - Imagens em Coluna'), ('layout3', 'Layout 3 - Imagens em Grade')], default='layout1', max_length=20)),
                ('estilo', models.IntegerField(default=1, help_text='Escolha entre 1 e 3 estilos disponíveis', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('imagem1', models.ImageField(blank=True, null=True, upload_to='editoriais/')),
                ('imagem2', models.ImageField(blank=True, null=True, upload_to='editoriais/')),
                ('imagem3', models.ImageField(blank=True, null=True, upload_to='editoriais/')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('agendado', 'Agendado'), ('publicado', 'Publicado'), ('desativado', 'Desativado')], default='rascunho', max_length=20)),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('agendado', models.BooleanField(default=False)),
                ('data_agendada', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('temas', models.ManyToManyField(related_name='editoriais', to='portal.tema')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriais',
                'ordering': ['-data_publicacao', '-data_criacao'],
                'indexes': [models.Index(fields=['-data_publicacao'], name='portal_edit_data_pu_6da2e5_idx'), models.Index(fields=['status'], name='portal_edit_status_30c9eb_idx'), models.Index(fields=['-visualizacoes'], name='portal_edit_visuali_fb25b4_idx')],
            },
        ),
    ]
