# Generated by Django 5.2.8 on 2025-11-28 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='altura_logo_header',
            field=models.IntegerField(default=80, help_text='Altura da área do logo header em pixels (50-200px recomendado)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
